from __future__ import annotations
import argparse

import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
import pandas as pd

# ============================================================================
# PATHS & CONFIGURATION
# ============================================================================

TOKENIZER_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = TOKENIZER_DIR.parent
DATA_DIR = PROJECT_ROOT / "data"


PROCESSED_DIR = DATA_DIR / "processed"

TRAIN_CSV = PROCESSED_DIR / "train.csv"
VALID_CSV = PROCESSED_DIR / "valid.csv"
TEST_CSV = PROCESSED_DIR / "test.csv"


CORPUS_PATH = TOKENIZER_DIR / "translator_train_corpus.txt"
MODEL_PREFIX = TOKENIZER_DIR / "translator_sp"


MODEL_PATH = MODEL_PREFIX.with_suffix(".model")
VOCAB_PATH = MODEL_PREFIX.with_suffix(".vocab")
METADATA_PATH = TOKENIZER_DIR / "translator_sp.metadata.json"


TOKENIZED_DIR = TOKENIZER_DIR / "tokenized"


# Separate tokenized text output files (subword pieces)
TRAIN_SRC_TOK = TOKENIZED_DIR / "amharic.train.tok.txt"
TRAIN_TGT_TOK = TOKENIZED_DIR / "afan_oromo.train.tok.txt"

VALID_SRC_TOK = TOKENIZED_DIR / "amharic.valid.tok.txt"
VALID_TGT_TOK = TOKENIZED_DIR / "afan_oromo.valid.tok.txt"

TEST_SRC_TOK = TOKENIZED_DIR / "amharic.test.tok.txt"
TEST_TGT_TOK = TOKENIZED_DIR / "afan_oromo.test.tok.txt"


# Separate token ID output files (integer sequences)
TRAIN_SRC_IDS = TOKENIZED_DIR / "amharic.train.ids.txt"
TRAIN_TGT_IDS = TOKENIZED_DIR / "afan_oromo.train.ids.txt"

VALID_SRC_IDS = TOKENIZED_DIR / "amharic.valid.ids.txt"
VALID_TGT_IDS = TOKENIZED_DIR / "afan_oromo.valid.ids.txt"

TEST_SRC_IDS = TOKENIZED_DIR / "amharic.test.ids.txt"
TEST_TGT_IDS = TOKENIZED_DIR / "afan_oromo.test.ids.txt"


# ============================================================================
# DATA / TOKENIZER CONFIGURATION
# ============================================================================


SOURCE_COLUMN = "Amharic"
TARGET_COLUMN = "Oromo"
VOCAB_SIZE = 10_000


MODEL_TYPE = "unigram"


CHARACTER_COVERAGE = 1.0


MAX_SENTENCE_LENGTH = 256


# Maximum number of SentencePiece tokens allowed
# in either source or target sentence.
MAX_TOKENS_PER_SENTENCE = 256


# Special token IDs
PAD_ID = 0
UNK_ID = 1
BOS_ID = 2
EOS_ID = 3


PAD_PIECE = "<pad>"
UNK_PIECE = "<unk>"
BOS_PIECE = "<bos>"
EOS_PIECE = "<eos>"

# ============================================================================
# DATA CLASSES
# ============================================================================

@dataclass
class DatasetStats:
    input_pairs: int = 0
    empty_pairs_removed: int = 0
    tokenized_pairs: int = 0
    filtered_long_pairs: int = 0

    source_avg_tokens: float = 0.0
    target_avg_tokens: float = 0.0

    source_min_tokens: int = 0
    source_max_tokens: int = 0

    target_min_tokens: int = 0
    target_max_tokens: int = 0


@dataclass
class TokenizerStats:
    train: DatasetStats
    valid: DatasetStats
    test: DatasetStats


# ============================================================================
# DEPENDENCY
# ============================================================================


def load_sentencepiece():
    """Import SentencePiece with a clear installation message."""
    try:
        import sentencepiece as spm
        return spm
    except ImportError as exc:
        raise ImportError(
            "SentencePiece is not installed.\n"
            "Install it with:\n"
            "    pip install sentencepiece"
        ) from exc


# ============================================================================
# DIRECTORY MANAGEMENT
# ============================================================================


def ensure_directories() -> None:
    """Create required directories."""
    TOKENIZER_DIR.mkdir(parents=True, exist_ok=True)
    TOKENIZED_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================================
# CLEAN OLD OUTPUTS
# ============================================================================


def remove_existing_outputs() -> None:
    """
    Remove outputs generated by this tokenizer pipeline.

    The original train/valid/test CSV files are NEVER removed.
    """

    files_to_remove = [
        CORPUS_PATH,
        MODEL_PATH,
        VOCAB_PATH,
        METADATA_PATH,

        TRAIN_SRC_TOK,
        TRAIN_TGT_TOK,

        VALID_SRC_TOK,
        VALID_TGT_TOK,

        TEST_SRC_TOK,
        TEST_TGT_TOK,

        TRAIN_SRC_IDS,
        TRAIN_TGT_IDS,

        VALID_SRC_IDS,
        VALID_TGT_IDS,

        TEST_SRC_IDS,
        TEST_TGT_IDS,
    ]

    removed = []

    for path in files_to_remove:
        if path.exists():
            path.unlink()
            removed.append(path)

    if removed:
        print("\n🧹 Removed previous tokenizer outputs:")

        for path in removed:
            print(f"   ✓ {path}")


# ============================================================================
# LOAD PARALLEL DATA
# ============================================================================


def load_parallel_csv(
    path: Path,
) -> tuple[list[str], list[str], int]:

    if not path.is_file():
        raise FileNotFoundError(
            f"Required dataset not found:\n{path}"
        )

    print(f"📂 Loading: {path}")

    df = pd.read_csv(path, encoding="utf-8")

    # Clean column names
    df.columns = [
        str(column).strip()
        for column in df.columns
    ]

    missing = {
        SOURCE_COLUMN,
        TARGET_COLUMN,
    }.difference(df.columns)

    if missing:
        raise ValueError(
            f"Missing required column(s) in {path.name}: "
            f"{sorted(missing)}"
        )

    source_sentences: list[str] = []
    target_sentences: list[str] = []

    empty_pairs_removed = 0

    for source, target in zip(
        df[SOURCE_COLUMN],
        df[TARGET_COLUMN],
    ):
        # Data is already normalized during preprocessing.
        if pd.isna(source) or pd.isna(target):
            empty_pairs_removed += 1
            continue

        source = str(source)
        target = str(target)

        if not source or not target:
            empty_pairs_removed += 1
            continue

        source_sentences.append(source)
        target_sentences.append(target)

    return (
        source_sentences,
        target_sentences,
        empty_pairs_removed,
    )


# ============================================================================
# BUILD TRAINING CORPUS
# ============================================================================


def build_training_corpus(
    train_src: list[str],
    train_tgt: list[str],
    output_path: Path = CORPUS_PATH,
) -> int:

    if len(train_src) != len(train_tgt):
        raise ValueError(
            "Source and target training data are not aligned."
        )

    sentence_count = 0

    with output_path.open(
        "w",
        encoding="utf-8",
        newline="\n",
    ) as file:

        # Amharic
        for sentence in train_src:
            file.write(sentence + "\n")
            sentence_count += 1

        # Afaan Oromo
        for sentence in train_tgt:
            file.write(sentence + "\n")
            sentence_count += 1

    if sentence_count == 0:
        raise ValueError(
            "Training corpus is empty."
        
        )

    return sentence_count

# ============================================================================
# TRAIN SENTENCEPIECE
# ============================================================================

def train_sentencepiece(
    corpus_path: Path = CORPUS_PATH,
    model_prefix: Path = MODEL_PREFIX,
    vocab_size: int = VOCAB_SIZE,
) -> None:
    """
    Train one joint SentencePiece Unigram tokenizer.

    The tokenizer is learned ONLY from train.csv.
    """

    spm = load_sentencepiece()

    if not corpus_path.is_file():
        raise FileNotFoundError(
            f"Training corpus not found: {corpus_path}"
        )

    if vocab_size <= 0:
        raise ValueError(
            "Vocabulary size must be greater than zero."
        )

    print(
        f"⚙️ Training SentencePiece "
        f"{MODEL_TYPE.upper()} tokenizer..."
    )

    print(
        f"   Vocabulary size      : {vocab_size:,}"
    )

    print(
        f"   Character coverage   : "
        f"{CHARACTER_COVERAGE}"
    )

    print(
        f"   Training corpus      : "
        f"{corpus_path}"
    )
    spm.SentencePieceTrainer.train(
        input=str(corpus_path),
        model_prefix=str(model_prefix),

        # Model
        model_type=MODEL_TYPE,
        vocab_size=vocab_size,

        # Character handling
        character_coverage=CHARACTER_COVERAGE,

        # SentencePiece normalization
        normalization_rule_name="nmt_nfkc",

        # Special tokens
        pad_id=PAD_ID,
        unk_id=UNK_ID,
        bos_id=BOS_ID,
        eos_id=EOS_ID,

        pad_piece=PAD_PIECE,
        unk_piece=UNK_PIECE,
        bos_piece=BOS_PIECE,
        eos_piece=EOS_PIECE,

        # Vocabulary behavior
        hard_vocab_limit=False,

        # Robustness for unusual Unicode characters
        byte_fallback=False,

        # Whitespace handling
        remove_extra_whitespaces=True,

        # Training behavior
        shuffle_input_sentence=True,

        # Avoid excessive logging
        train_extremely_large_corpus=False,
    )

    print(
        f"✓ Tokenizer model created: "
        f"{model_prefix}.model"
    )

    print(
        f"✓ Vocabulary created: "
        f"{model_prefix}.vocab"
    )


# ============================================================================
# LOAD TOKENIZER
# ============================================================================


def load_tokenizer(model_path: Path = MODEL_PATH):
    """Load a trained SentencePiece model."""

    if not model_path.is_file():
        raise FileNotFoundError(
            f"Tokenizer model not found: {model_path}"
        )

    spm = load_sentencepiece()

    return spm.SentencePieceProcessor(
        model_file=str(model_path)
    )

# ============================================================================
# VALIDATE TOKENIZER
# ============================================================================
def validate_tokenizer(
    model_path: Path = MODEL_PATH,
    expected_vocab_size: int = VOCAB_SIZE,
) -> dict:
    """
    Verify:
      - model loads
      - vocabulary size
      - special token IDs
      - special token pieces
    """

    sp = load_tokenizer(model_path)

    actual_specials = {
        "pad": sp.pad_id(),
        "unk": sp.unk_id(),
        "bos": sp.bos_id(),
        "eos": sp.eos_id(),
    }

    expected_specials = {
        "pad": PAD_ID,
        "unk": UNK_ID,
        "bos": BOS_ID,
        "eos": EOS_ID,
    }

    if actual_specials != expected_specials:
        raise RuntimeError(
            "Special token ID mismatch.\n"
            f"Expected: {expected_specials}\n"
            f"Actual:   {actual_specials}"
        )

    actual_pieces = {
        "pad": sp.id_to_piece(PAD_ID),
        "unk": sp.id_to_piece(UNK_ID),
        "bos": sp.id_to_piece(BOS_ID),
        "eos": sp.id_to_piece(EOS_ID),
    }

    expected_pieces = {
        "pad": PAD_PIECE,
        "unk": UNK_PIECE,
        "bos": BOS_PIECE,
        "eos": EOS_PIECE,
    }

    if actual_pieces != expected_pieces:
        raise RuntimeError(
            "Special token piece mismatch.\n"
            f"Expected: {expected_pieces}\n"
            f"Actual:   {actual_pieces}"
        )

    actual_vocab_size = sp.get_piece_size()

    if actual_vocab_size != expected_vocab_size:
        raise RuntimeError(
            f"Vocabulary size mismatch.\n"
            f"Expected: {expected_vocab_size:,}\n"
            f"Actual:   {actual_vocab_size:,}"
        )

    return {
        "vocab_size": actual_vocab_size,
        "special_tokens": actual_specials,
        "special_pieces": actual_pieces,
    }


# ============================================================================
# TOKENIZE PARALLEL DATA (WITH SEPARATE OUTPUT)
# ============================================================================


def tokenize_parallel_data(
    source_sentences: list[str],
    target_sentences: list[str],
    sp,
    max_tokens: int = MAX_TOKENS_PER_SENTENCE,
    src_tok_out: Path | None = None,
    tgt_tok_out: Path | None = None,
    src_ids_out: Path | None = None,
    tgt_ids_out: Path | None = None,
) -> tuple[list[list[str]], list[list[str]], DatasetStats]:
    """
    Tokenize source-target pairs and save them as separate source/target files.

    A pair is removed if either side exceeds max_tokens.

    Source and target always remain aligned.

    Outputs:
      - src_tok_out: source tokens (space-separated pieces), one sentence per line
      - tgt_tok_out: target tokens (space-separated pieces), one sentence per line
      - src_ids_out: source token IDs (space-separated ints), one sentence per line
      - tgt_ids_out: target token IDs (space-separated ints), one sentence per line

    Encoding is done only once per sentence (2 calls per pair).
    Pieces are derived from IDs using id_to_piece().
    """

    if len(source_sentences) != len(target_sentences):
        raise ValueError(
            "Source and target sentence counts do not match."
        )

    source_tokens: list[list[str]] = []
    target_tokens: list[list[str]] = []

    source_lengths: list[int] = []
    target_lengths: list[int] = []

    filtered_long_pairs = 0

    src_tok_file = None
    tgt_tok_file = None
    src_ids_file = None
    tgt_ids_file = None

    if src_tok_out is not None:
        src_tok_out.parent.mkdir(parents=True, exist_ok=True)
        src_tok_file = src_tok_out.open(
            "w",
            encoding="utf-8",
            newline="\n",
        )

    if tgt_tok_out is not None:
        tgt_tok_out.parent.mkdir(parents=True, exist_ok=True)
        tgt_tok_file = tgt_tok_out.open(
            "w",
            encoding="utf-8",
            newline="\n",
        )

    if src_ids_out is not None:
        src_ids_out.parent.mkdir(parents=True, exist_ok=True)
        src_ids_file = src_ids_out.open(
            "w",
            encoding="utf-8",
            newline="\n",
        )

    if tgt_ids_out is not None:
        tgt_ids_out.parent.mkdir(parents=True, exist_ok=True)
        tgt_ids_file = tgt_ids_out.open(
            "w",
            encoding="utf-8",
            newline="\n",
        )

    try:
        for source, target in zip(
            source_sentences,
            target_sentences,
        ):

            # Encode once per sentence to IDs
            src_ids = sp.encode(
                source,
                out_type=int,
            )

            tgt_ids = sp.encode(
                target,
                out_type=int,
            )

            # Derive pieces from IDs
            src_pieces = [
                sp.id_to_piece(i)
                for i in src_ids
            ]

            tgt_pieces = [
                sp.id_to_piece(i)
                for i in tgt_ids
            ]

            if (
                len(src_pieces) > max_tokens
                or len(tgt_pieces) > max_tokens
            ):
                filtered_long_pairs += 1
                continue

            source_tokens.append(src_pieces)
            target_tokens.append(tgt_pieces)

            source_lengths.append(len(src_pieces))
            target_lengths.append(len(tgt_pieces))

            # Write token pieces
            if src_tok_file is not None:
                src_tok_file.write(
                    " ".join(src_pieces) + "\n"
                )

            if tgt_tok_file is not None:
                tgt_tok_file.write(
                    " ".join(tgt_pieces) + "\n"
                )

            # Write token IDs
            if src_ids_file is not None:
                src_ids_file.write(
                    " ".join(map(str, src_ids)) + "\n"
                )

            if tgt_ids_file is not None:
                tgt_ids_file.write(
                    " ".join(map(str, tgt_ids)) + "\n"
                )

        stats = DatasetStats(
            input_pairs=len(source_sentences),
            tokenized_pairs=len(source_tokens),
            filtered_long_pairs=filtered_long_pairs,
        )

        if source_lengths:

            stats.source_avg_tokens = round(
                sum(source_lengths) / len(source_lengths),
                2,
            )

            stats.target_avg_tokens = round(
                sum(target_lengths) / len(target_lengths),
                2,
            )

            stats.source_min_tokens = min(source_lengths)
            stats.source_max_tokens = max(source_lengths)

            stats.target_min_tokens = min(target_lengths)
            stats.target_max_tokens = max(target_lengths)

        return (
            source_tokens,
            target_tokens,
            stats,
        )

    finally:

        if src_tok_file is not None:
            src_tok_file.close()

        if tgt_tok_file is not None:
            tgt_tok_file.close()

        if src_ids_file is not None:
            src_ids_file.close()

        if tgt_ids_file is not None:
            tgt_ids_file.close()


# ============================================================================
# ENCODE / DECODE TEST
# ============================================================================


def test_roundtrip(
    sp,
) -> dict:
    """
    Verify that SentencePiece can encode and decode
    representative Amharic and Oromo examples.
    """

    samples = [
        "ሰላም እንደምን ነህ?",
        "ትምህርት ቤት ሄደ።",
        "akkaan jirtaa?",
        "galatoomi!",
    ]

    results = {}

    for text in samples:

        ids = sp.encode(
            text,
            out_type=int,
        )

        pieces = sp.encode(
            text,
            out_type=str,
        )

        decoded = sp.decode(ids)

        results[text] = {
            "token_ids": ids,
            "subword_pieces": pieces,
            "num_tokens": len(ids),
            "decoded_text": decoded,
            "roundtrip_match": text == decoded,
        }

    return results


# ============================================================================
# TOKENIZER CORPUS STATISTICS
# ============================================================================


def compute_corpus_statistics(
    sp,
    corpus_path: Path = CORPUS_PATH,
) -> dict:
    """
    Calculate statistics for the tokenizer training corpus.
    """

    lengths: list[int] = []

    with corpus_path.open(
        "r",
        encoding="utf-8",
    ) as file:

        for line in file:

            text = line.strip()

            if not text:
                continue

            ids = sp.encode(
                text,
                out_type=int,
            )

            lengths.append(len(ids))

    if not lengths:
        raise ValueError(
            "Cannot calculate token statistics: "
            "corpus contains no valid sentences."
        )

    return {
        "total_sentences": len(lengths),
        "avg_tokens_per_sentence": round(
            sum(lengths) / len(lengths),
            2,
        ),
        "min_tokens": min(lengths),
        "max_tokens": max(lengths),
    }


# ============================================================================
# PIPELINE
# ============================================================================


def run_pipeline(
    force: bool = False,
    vocab_size: int = VOCAB_SIZE,
) -> dict:

    print("\n" + "=" * 80)

    print(
        "AMHARIC → AFAAN OROMO "
        "SENTENCEPIECE TOKENIZATION PIPELINE"
    )

    print("=" * 80)

    ensure_directories()

    # ------------------------------------------------------------------------
    # 0. CHECK INPUT DATA
    # ------------------------------------------------------------------------

    print(
        "\n[0/6] Checking train/validation/test datasets..."
    )

    for path in [
        TRAIN_CSV,
        VALID_CSV,
        TEST_CSV,
    ]:

        if not path.is_file():
            raise FileNotFoundError(
                f"Required dataset not found: {path}"
            )

        print(f"   ✓ {path}")

    # ------------------------------------------------------------------------
    # 1. CLEAN OLD TOKENIZER OUTPUTS
    # ------------------------------------------------------------------------

    if force:

        print(
            "\n[1/6] Removing previous tokenizer outputs..."
        )

        remove_existing_outputs()

    elif MODEL_PATH.exists():

        raise FileExistsError(
            f"Tokenizer already exists:\n"
            f"{MODEL_PATH}\n\n"
            f"Use --force if you intentionally want "
            f"to retrain it."
        )

    else:

        print(
            "\n[1/6] No existing tokenizer model found."
        )

    # ------------------------------------------------------------------------
    # 2. LOAD SPLIT DATA
    # ------------------------------------------------------------------------

    print(
        "\n[2/6] Loading train/validation/test data..."
    )

    train_src, train_tgt, train_empty = load_parallel_csv(
        TRAIN_CSV
    )

    valid_src, valid_tgt, valid_empty = load_parallel_csv(
        VALID_CSV
    )

    test_src, test_tgt, test_empty = load_parallel_csv(
        TEST_CSV
    )

    print(
        f"   Train pairs: {len(train_src):,}"
    )

    print(
        f"   Valid pairs: {len(valid_src):,}"
    )

    print(
        f"   Test pairs : {len(test_src):,}"
    )

    # ------------------------------------------------------------------------
    # 3. BUILD TRAINING CORPUS
    # ------------------------------------------------------------------------

    print(
        "\n[3/6] Building JOINT tokenizer training corpus..."
    )

    print(
        "   ⚠️ Only TRAIN data is used to learn the vocabulary."
    )

    print(
        "   ✓ Amharic training sentences"
    )

    print(
        "   ✓ Afaan Oromo training sentences"
    )

    print(
        "   ✗ Validation data is NOT used"
    )

    print(
        "   ✗ Test data is NOT used"
    )

    sentence_count = build_training_corpus(
        train_src,
        train_tgt,
        CORPUS_PATH,
    )

    print(
        f"✓ Training corpus created: "
        f"{sentence_count:,} sentences"
    )

    # ------------------------------------------------------------------------
    # 4. TRAIN TOKENIZER
    # ------------------------------------------------------------------------

    print(
        "\n[4/6] Training SentencePiece tokenizer..."
    )

    train_sentencepiece(
        corpus_path=CORPUS_PATH,
        model_prefix=MODEL_PREFIX,
        vocab_size=vocab_size,
    )

    # ------------------------------------------------------------------------
    # 5. VALIDATE + TOKENIZE
    # ------------------------------------------------------------------------

    print(
        "\n[5/6] Validating tokenizer and tokenizing datasets..."
    )

    sp = load_tokenizer(MODEL_PATH)

    validation_info = validate_tokenizer(
        MODEL_PATH,
        expected_vocab_size=vocab_size,
    )

    print(
        f"   ✓ Vocabulary: "
        f"{validation_info['vocab_size']:,}"
    )

    print(
        f"   ✓ Special token IDs verified"
    )

    # Tokenize train (separate src/tgt tok + ids)
    train_src_tok, train_tgt_tok, train_stats = tokenize_parallel_data(
        train_src,
        train_tgt,
        sp,
        src_tok_out=TRAIN_SRC_TOK,
        tgt_tok_out=TRAIN_TGT_TOK,
        src_ids_out=TRAIN_SRC_IDS,
        tgt_ids_out=TRAIN_TGT_IDS,
    )

    # Tokenize validation (separate src/tgt tok + ids)
    valid_src_tok, valid_tgt_tok, valid_stats = tokenize_parallel_data(
        valid_src,
        valid_tgt,
        sp,
        src_tok_out=VALID_SRC_TOK,
        tgt_tok_out=VALID_TGT_TOK,
        src_ids_out=VALID_SRC_IDS,
        tgt_ids_out=VALID_TGT_IDS,
    )

    # Tokenize test (separate src/tgt tok + ids)
    test_src_tok, test_tgt_tok, test_stats = tokenize_parallel_data(
        test_src,
        test_tgt,
        sp,
        src_tok_out=TEST_SRC_TOK,
        tgt_tok_out=TEST_TGT_TOK,
        src_ids_out=TEST_SRC_IDS,
        tgt_ids_out=TEST_TGT_IDS,
    )

    print(
        f"   ✓ Train tokenized (separate): "
        f"{train_stats.tokenized_pairs:,}"
    )

    print(
        f"   ✓ Valid tokenized (separate): "
        f"{valid_stats.tokenized_pairs:,}"
    )

    print(
        f"   ✓ Test tokenized (separate):  "
        f"{test_stats.tokenized_pairs:,}"
    )

    # ------------------------------------------------------------------------
    # 6. TEST + METADATA
    # ------------------------------------------------------------------------

    print(
        "\n[6/6] Running tokenizer tests..."
    )

    roundtrip_results = test_roundtrip(sp)

    failed_roundtrips = [
        text
        for text, result in roundtrip_results.items()
        if not result["roundtrip_match"]
    ]

    if failed_roundtrips:

        print(
            "⚠️ Some roundtrip tests did not exactly match."
        )

        for text in failed_roundtrips:
            print(f"   - {text}")

    else:

        print(
            "   ✓ All sample encode/decode tests passed."
        )

    corpus_stats = compute_corpus_statistics(
        sp,
        CORPUS_PATH,
    )

    tokenizer_stats = TokenizerStats(
        train=train_stats,
        valid=valid_stats,
        test=test_stats,
    )

    metadata = {

        "created_at": datetime.now(
            timezone.utc
        ).isoformat(),

        "task": "Amharic to Afaan Oromo Neural Machine Translation",

        "tokenizer": {
            "library": "SentencePiece",
            "model_type": MODEL_TYPE,
            "vocab_size": validation_info["vocab_size"],
            "character_coverage": CHARACTER_COVERAGE,
            "max_sentence_length": MAX_SENTENCE_LENGTH,
            "max_tokens_per_sentence": MAX_TOKENS_PER_SENTENCE,
        },

        "special_tokens": {

            "pad": {
                "piece": PAD_PIECE,
                "id": PAD_ID,
            },

            "unk": {
                "piece": UNK_PIECE,
                "id": UNK_ID,
            },

            "bos": {
                "piece": BOS_PIECE,
                "id": BOS_ID,
            },

            "eos": {
                "piece": EOS_PIECE,
                "id": EOS_ID,
            },
        },

        "input_datasets": {

            "train": str(
                TRAIN_CSV.resolve()
            ),

            "valid": str(
                VALID_CSV.resolve()
            ),

            "test": str(
                TEST_CSV.resolve()
            ),
        },

        "tokenizer_training": {

            "training_data": "TRAIN ONLY",

            "source_sentences": len(train_src),

            "target_sentences": len(train_tgt),

            "joint_corpus_sentences": sentence_count,

            "validation_used_for_training": False,

            "test_used_for_training": False,
        },

        "outputs": {

            "model": str(
                MODEL_PATH.resolve()
            ),

            "vocab": str(
                VOCAB_PATH.resolve()
            ),

            "corpus": str(
                CORPUS_PATH.resolve()
            ),

            "metadata": str(
                METADATA_PATH.resolve()
            ),

            "train_source_tok": str(
                TRAIN_SRC_TOK.resolve()
            ),

            "train_target_tok": str(
                TRAIN_TGT_TOK.resolve()
            ),

            "train_source_ids": str(
                TRAIN_SRC_IDS.resolve()
            ),

            "train_target_ids": str(
                TRAIN_TGT_IDS.resolve()
            ),

            "valid_source_tok": str(
                VALID_SRC_TOK.resolve()
            ),

            "valid_target_tok": str(
                VALID_TGT_TOK.resolve()
            ),

            "valid_source_ids": str(
                VALID_SRC_IDS.resolve()
            ),

            "valid_target_ids": str(
                VALID_TGT_IDS.resolve()
            ),

            "test_source_tok": str(
                TEST_SRC_TOK.resolve()
            ),

            "test_target_tok": str(
                TEST_TGT_TOK.resolve()
            ),

            "test_source_ids": str(
                TEST_SRC_IDS.resolve()
            ),

            "test_target_ids": str(
                TEST_TGT_IDS.resolve()
            ),
        },

        "empty_pairs_removed": {

            "train": train_empty,

            "valid": valid_empty,

            "test": test_empty,
        },

        "dataset_statistics": asdict(
            tokenizer_stats
        ),

        "corpus_statistics": corpus_stats,

        "sample_tokenizations": roundtrip_results,

        "status": "passed",
    }

    METADATA_PATH.write_text(
        json.dumps(
            metadata,
            indent=2,
            ensure_ascii=False,
        ) + "\n",
        encoding="utf-8",
    )

    print(
        f"✓ Metadata saved: {METADATA_PATH}"
    )

    return metadata


# ============================================================================
# SUMMARY
# ============================================================================


def print_summary(metadata: dict) -> None:

    print("\n" + "=" * 80)

    print(
        "TOKENIZATION COMPLETED"
    )

    print("=" * 80)

    print(
        f"Tokenizer             : "
        f"{metadata['tokenizer']['model_type'].upper()}"
    )

    print(
        f"Vocabulary size       : "
        f"{metadata['tokenizer']['vocab_size']:,}"
    )

    print(
        f"Maximum tokens/sent.  : "
        f"{metadata['tokenizer']['max_tokens_per_sentence']}"
    )

    print("\nSpecial Tokens:")

    specials = metadata["special_tokens"]

    print(
        f"  {PAD_PIECE:<10} → "
        f"{specials['pad']['id']}"
    )

    print(
        f"  {UNK_PIECE:<10} → "
        f"{specials['unk']['id']}"
    )

    print(
        f"  {BOS_PIECE:<10} → "
        f"{specials['bos']['id']}"
    )

    print(
        f"  {EOS_PIECE:<10} → "
        f"{specials['eos']['id']}"
    )

    for split in [
        "train",
        "valid",
        "test",
    ]:

        stats = metadata[
            "dataset_statistics"
        ][split]

        print(f"\n--- {split.upper()} ---")

        print(
            f"Input pairs          : "
            f"{stats['input_pairs']:,}"
        )

        print(
            f"Tokenized pairs      : "
            f"{stats['tokenized_pairs']:,}"
        )

        print(
            f"Filtered long pairs  : "
            f"{stats['filtered_long_pairs']:,}"
        )

        print(
            f"Avg source tokens    : "
            f"{stats['source_avg_tokens']}"
        )

        print(
            f"Avg target tokens    : "
            f"{stats['target_avg_tokens']}"
        )

        print(
            f"Source token range   : "
            f"{stats['source_min_tokens']} - "
            f"{stats['source_max_tokens']}"
        )

        print(
            f"Target token range   : "
            f"{stats['target_min_tokens']} - "
            f"{stats['target_max_tokens']}"
        )

    print("\nOutput Files:")

    print(
        f"  Model           : "
        f"{MODEL_PATH}"
    )

    print(
        f"  Vocabulary      : "
        f"{VOCAB_PATH}"
    )

    print(
        f"  Train corpus    : "
        f"{CORPUS_PATH}"
    )

    print(
        f"  Metadata        : "
        f"{METADATA_PATH}"
    )

    print(
        f"  Tokenized dir   : "
        f"{TOKENIZED_DIR}"
    )

    print("\n" + "=" * 80)

    print(
        "✓ TOKENIZER PIPELINE PASSED"
    )

    print("=" * 80 + "\n")


# ============================================================================
# COMMAND LINE
# ============================================================================


def parse_args() -> argparse.Namespace:

    parser = argparse.ArgumentParser(
        description=(
            "Train a joint SentencePiece Unigram tokenizer "
            "for Amharic → Afaan Oromo translation."
        )
    )

    parser.add_argument(
        "--vocab-size",
        type=int,
        default=VOCAB_SIZE,
        help="Vocabulary size (default: 10,000)",
    )

    parser.add_argument(
        "--force",
        action="store_true",
        help=(
            "Delete existing tokenizer outputs and "
            "retrain the tokenizer."
        ),
    )

    return parser.parse_args()


# ============================================================================
# MAIN
# ============================================================================


def main() -> None:

    args = parse_args()

    try:

        metadata = run_pipeline(
            force=args.force,
            vocab_size=args.vocab_size,
        )

        print_summary(metadata)

    except Exception as exc:

        print(
            "\n❌ Tokenizer pipeline failed:"
        )

        print(
            f"   {exc}\n"
        )

        raise


if __name__ == "__main__":
    main()